let countryColors = {
  "#f78d94": ["Eastern Africa","Burundi", "Comoros", "Djibouti", "Eritrea", "Ethiopia", "Kenya", "Madagascar", "Malawi", "Mauritius","Mayotte", "Mozambique", "Réunion", "Rwanda", "Seychelles", "Somalia", "South Sudan", "Uganda", "United Republic of Tanzania", "Zambia", "Zimbabwe"],
  "#fcad9a": ["Middle Africa","Angola", "Cameroon" , "Central African Republic" ,"Chad" , "Congo" , "Democratic Republic of the Congo" , "Equatorial Guinea" ,"Gabon" ,"Sao Tome and Principe"],
  "#ffd6cf": ["Nothern Africa","Algeria" , "Egypt" ,"Libya", "Morocco", "Sudan","Tunisia" , "Western Sahara"],
  "#ed7f74": ["Southern Africa","Botswana","Eswatini" ,"Lesotho" ,"Namibia" , "South Africa"],
  "#ffc4b6": ["Western Africa","Benin" , "Burkina Faso" ,"Cabo Verde" , "Côte d'Ivoire" , "Gambia" ,"Ghana" , "Guinea", "Guinea-Bissau" ,"Liberia" ,"Mali" , "Mauritania" ,"Niger" , "Nigeria" , "Saint Helena" , "Senegal", "Sierra Leone" , "Togo"],
  "#49c98f": ["North America","Bermuda",
"Canada", "Greenland",
"Saint Pierre and Miquelon", "United States of America"],
    "#8ded4f": ["Central America","Belize" , "Costa Rica",
"El Salvador", "Guatemala",
"Honduras", "Mexico",
"Nicaragua", "Panama"],
      "#ffffa1": ["South America","Argentina",
"Bolivia","Brazil","Chile", "Colombia","Ecuador", "Malvinas","French Guiana", "Guyana","Paraguay", "Peru","Suriname", "Uruguay",
"Venezuela"],
        "#e5f761": ["Caribbean","Anguilla","Antigua and Barbuda", "Aruba","Bahamas", "Barbados", 
"British Virgin Islands" , "Cayman Islands","Cuba", "Curaçao",
"Dominica", "Dominican Republic","Grenada", "Guadeloupe","Haiti", "Jamaica",
"Martinique", "Montserrat","Puerto Rico", "Saint Kitts and Nevis",
"Saint Lucia,", "Saint Vincent and the Grenadines","Sint Maarten", "Trinidad and Tobago","Turks and Caicos Islands", "United States Virgin Islands"],
        "#25f4f4": ["Nothern Europe","Channel Islands" , "Denmark" , "Estonia","Faroe Islands" , "Finland" ,"Iceland" , "Ireland",
"Isle of Man", "Latvia" , "Lithuania", "Norway" , "Sweden", "United Kingdom"],
          "#6ddcfc": ["Western Europe","Austria" , "Belgium" , "France" ,"Germany" , "Liechtenstein",
"Luxembourg" , "Monaco","Netherlands" , "Switzerland"],
            "#b6f1ff": ["Southern Europe","Albania" , "Andorra" ,"Bosnia and Herzegovina" ,"Croatia" , "Gibraltar",
"Greece" , "Italy", "Malta" , "Montenegro","North Macedonia" , "Portugal","San Marino", "Serbia","Slovenia" , "Spain"],
              "#34bde8": ["Eastern Europe","Belarus" , "Bulgaria" , "Czechia" ,"Hungary" , "Poland" , "Republic of Moldova" , "Romania", "Russian Federation", "Slovakia","Ukraine"],
              "#559aff": ["Central Asia","Kazakhstan" , "Kyrgyzstan" , "Tajikistan" ,"Turkmenistan" , "Uzbekistan"],
              "#4b7cf7": ["Eastern Asia","China" , "China, Hong Kong SAR", "China, Macao SAR", "China, Taiwan Province of China", "Dem. People's Republic of Korea" , "Japan" , "Mongolia" , "Republic of Korea"],
                "#aa83ff": ["Southern Asia","Afghanistan", "Bangladesh" , "Bhutan" ,"India" , "Iran" , "Maldives", "Nepal", "Pakistan", "Sri Lanka"],
                  "#7027e2": ["Southeastern Asia","Brunei Darussalam" , "Cambodia" , "Indonesia" , "Lao People's Democratic Republic", "Malaysia", "Myanmar", "Philippines" , "Singapore" , "Thailand" , "Timor-Leste" ,
"Viet Nam"],
                    "#c4b4f9": ["Western Asia","Armenia","Azerbaijan" ,"Bahrain" , "Cyprus", "Georgia",
"Iraq", "Israel", "Jordan", "Kuwait","Lebanon", "Oman","Qatar", "Saudi Arabia" , "State of Palestine", "Syrian Arab Republic" , "Türkiye", "United Arab Emirates" , "Yemen"],
  "#d84ef9": ["Australia & New Zealand","Australia", "New Zealand"],
    "#9e16bf": ["Fiji","New Caledonia", "Papua New Guinea","Solomon Islands", "Vanuatu", "Melanesia"],
      "#bf00c9": ["Guam","Kiribati", "Marshall Islands","Micronesia (Fed. States of)", "Nauru", "Northern Mariana Islands", "Palau","Micronesia"],
        "#f385ff": ["American Samoa",
"Cook Islands", "French Polynesia",
"Niue", "Samoa", "Tokelau", "Tonga" , "Tuvalu", "Wallis and Futuna Islands","Polynesia"],
};


let continents = {
  "Southern Africa": ["Botswana","Eswatini" ,"Lesotho" ,"Namibia" , "South Africa"],
  "Eastern Africa": ["Burundi", "Comoros", "Djibouti", "Eritrea", "Ethiopia", "Kenya", "Madagascar", "Malawi", "Mauritius","Mayotte", "Mozambique", "Réunion", "Rwanda", "Seychelles", "Somalia", "South Sudan", "Uganda", "United Republic of Tanzania", "Zambia", "Zimbabwe"],
  "Western Africa":  ["Benin" , "Burkina Faso" ,"Cabo Verde" , "Côte d'Ivoire" , "Gambia" ,"Ghana" , "Guinea", "Guinea-Bissau" ,"Liberia" ,"Mali" , "Mauritania" ,"Niger" , "Nigeria" , "Saint Helena" , "Senegal", "Sierra Leone" , "Togo"],
    "Nothern Africa": ["Algeria" , "Egypt" ,"Libya", "Morocco", "Sudan","Tunisia" , "Western Sahara"],
  "Middle Africa": ["Angola", "Cameroon" , "Central African Republic" ,"Chad" , "Congo" , "Democratic Republic of the Congo" , "Equatorial Guinea" ,"Gabon" ,"Sao Tome and Principe"],
    "Melanesia": ["Fiji","New Caledonia", "Papua New Guinea","Solomon Islands", "Vanuatu"],
      "Australia & New Zealand": ["Australia", "New Zealand"],
  "Polynesia" : ["American Samoa",
"Cook Islands", "French Polynesia",
"Niue", "Samoa", "Tokelau", "Tonga" , "Tuvalu", "Wallis and Futuna Islands"],
  "Micronesia" : ["Guam","Kiribati", "Marshall Islands","Micronesia (Fed. States of)", "Nauru", "Northern Mariana Islands", "Palau"],
  "Southeastern Asia" :["Brunei Darussalam" , "Cambodia" , "Indonesia" , "Lao People's Democratic Republic", "Malaysia", "Myanmar", "Philippines" , "Singapore" , "Thailand" , "Timor-Leste" ,
"Viet Nam"],
  "Western Asia" : ["Armenia","Azerbaijan" ,"Bahrain" , "Cyprus", "Georgia",
"Iraq", "Israel", "Jordan", "Kuwait","Lebanon", "Oman","Qatar", "Saudi Arabia" , "State of Palestine", "Syrian Arab Republic" , "Türkiye", "United Arab Emirates" , "Yemen"],
  "Central Asia" :["Kazakhstan" , "Kyrgyzstan" , "Tajikistan" ,"Turkmenistan" , "Uzbekistan"],
  "Southern Asia" :["Afghanistan", "Bangladesh" , "Bhutan" ,"India" , "Iran" , "Maldives", "Nepal", "Pakistan", "Sri Lanka"],
  "Eastern Asia" :["China" , "China, Hong Kong SAR", "China, Macao SAR", "China, Taiwan Province of China", "Dem. People's Republic of Korea" , "Japan" , "Mongolia" , "Republic of Korea"],
  "Eastern Europe" : ["Belarus" , "Bulgaria" , "Czechia" ,"Hungary" , "Poland" , "Republic of Moldova" , "Romania", "Russian Federation", "Slovakia","Ukraine"],
  "Southern Europe" :["Albania" , "Andorra" ,"Bosnia and Herzegovina" ,"Croatia" , "Gibraltar",
"Greece" , "Italy", "Malta" , "Montenegro","North Macedonia" , "Portugal","San Marino", "Serbia","Slovenia" , "Spain"],
  "Western Europe" : ["Austria" , "Belgium" , "France" ,"Germany" , "Liechtenstein",
"Luxembourg" , "Monaco","Netherlands" , "Switzerland"],
  "Nothern Europe":  ["Channel Islands" , "Denmark" , "Estonia","Faroe Islands" , "Finland" ,"Iceland" , "Ireland","Isle of Man", "Latvia" , "Lithuania", "Norway" , "Sweden", "United Kingdom"],
  "South America" : ["Argentina",
"Bolivia","Brazil","Chile", "Colombia","Ecuador", "Malvinas","French Guiana", "Guyana","Paraguay", "Peru","Suriname", "Uruguay",
"Venezuela"],
  "Caribbean" : ["Anguilla","Antigua and Barbuda", "Aruba","Bahamas", "Barbados", 
"British Virgin Islands" , "Cayman Islands","Cuba", "Curaçao",
"Dominica", "Dominican Republic","Grenada", "Guadeloupe","Haiti", "Jamaica",
"Martinique", "Montserrat","Puerto Rico", "Saint Kitts and Nevis",
"Saint Lucia", "Saint Vincent and the Grenadines","Sint Maarten", "Trinidad and Tobago","Turks and Caicos Islands", "United States Virgin Islands"],
  "Central America": ["Belize" , "Costa Rica",
"El Salvador", "Guatemala",
"Honduras", "Mexico",
"Nicaragua", "Panama"],
  "North America" : ["Bermuda",
"Canada", "Greenland",
"Saint Pierre and Miquelon", "United States of America"]
};
